// Initial data for Umbra HQ

export interface Project {
  id: string;
  name: string;
  description: string;
  status: 'active' | 'completed' | 'on-hold';
  githubUrl?: string;
  vercelUrl?: string;
  notes: string;
  details?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Document {
  id: string;
  title: string;
  category: 'audits' | 'research' | 'marketing' | 'technical' | 'other';
  url?: string;
  description: string;
  content?: string;
  createdAt: string;
  updatedAt?: string;
}

export interface Update {
  id: string;
  content: string;
  timestamp: string;
  type: 'status' | 'task' | 'note' | 'milestone';
}

export interface QuickLink {
  id: string;
  label: string;
  url: string;
  category: 'site' | 'repo' | 'tool' | 'docs' | 'resource';
  description?: string;
}

export interface Blocker {
  id: string;
  title: string;
  description: string;
  severity: 'critical' | 'high' | 'medium';
  category: 'billing' | 'access' | 'rate-limit' | 'account' | 'technical' | 'other';
  createdAt: string;
  resolved: boolean;
}

export interface DailyBriefing {
  date: string;
  summary: string;
  keyItems: string[];
  whatsNext: string[];
  mood: 'productive' | 'blocked' | 'planning' | 'shipping';
}

export interface Task {
  id: string;
  title: string;
  description?: string;
  status: 'todo' | 'in-progress' | 'done';
  priority: 'low' | 'medium' | 'high';
  projectId?: string;
  createdAt: string;
  updatedAt: string;
}

export const initialProjects: Project[] = [
  {
    id: '1',
    name: 'Demo Site',
    description: 'Interactive demo showcasing Umbra capabilities and features',
    status: 'active',
    githubUrl: 'https://github.com/umbrarelay-maker/apex-digital-demo',
    vercelUrl: 'https://apex-digital-demo.vercel.app',
    notes: 'Main showcase for potential users. Needs polishing.',
    details: `## Overview
The Demo Site serves as the primary showcase for Umbra's capabilities. It demonstrates real-time AI collaboration, tool usage, and autonomous task completion.

## Current State
- Basic structure deployed
- Hero section with feature highlights
- Interactive demo components in progress

## Next Steps
1. Add live demo of conversation flow
2. Showcase tool integrations
3. Add testimonials/use cases section
4. Performance optimization

## Tech Stack
- Next.js 16
- Tailwind CSS
- Framer Motion for animations`,
    createdAt: '2026-02-03T00:00:00Z',
    updatedAt: '2026-02-03T05:00:00Z'
  },
  {
    id: '2',
    name: 'Report Viewer',
    description: 'Web interface for viewing and navigating generated reports',
    status: 'active',
    githubUrl: 'https://github.com/umbrarelay-maker/report-viewer',
    vercelUrl: 'https://report-viewer-two.vercel.app',
    notes: 'Renders markdown reports with navigation. MVP complete.',
    details: `## Overview
A clean, readable interface for viewing markdown reports generated by Umbra. Supports navigation, search, and categorization.

## Current State
- MVP deployed and functional
- Markdown rendering working
- Basic navigation implemented

## Features
- Markdown to HTML conversion
- Table of contents generation
- Print-friendly styling
- Dark/light mode

## Next Steps
1. Add search functionality
2. PDF export option
3. Report comparison view`,
    createdAt: '2026-02-03T00:00:00Z',
    updatedAt: '2026-02-03T04:30:00Z'
  },
  {
    id: '3',
    name: 'Nyx Chat',
    description: 'AI chatbot platform with RAG knowledge base - white-label product for clients',
    status: 'active',
    githubUrl: 'https://github.com/umbrarelay-maker/chatbot-framework',
    vercelUrl: 'https://chatbot-framework-one.vercel.app',
    notes: 'Rebranded to Nyx Chat. Multi-provider AI, RAG pipeline, URL import ready. Needs auth before production.',
    details: `## Overview
Nyx Chat is a white-label AI chatbot platform that clients can configure and embed on their websites. Competes with WebFX's AI Agent services at better pricing.

## Features (Built)
- Multi-provider AI (GPT-5.2, Claude Haiku 4.5, Gemini 3 Flash)
- Client-provided API keys
- Customizable widget (7 icons, brand colors)
- Knowledge base with text paste + URL import
- RAG pipeline (pgvector ready)
- Dark, sophisticated UI

## Tech Stack
- Next.js + Tailwind
- Supabase (pgvector for RAG)
- Mozilla Readability for URL scraping
- OpenAI/Anthropic/Google APIs

## Before Production
- [ ] Auth/accounts (Supabase Auth)
- [ ] API key encryption
- [ ] Run SQL schema in Supabase
- [ ] Test with real API keys
- [ ] Create embeddable widget.js
- [ ] Custom domain (exploring options)

## Pricing Strategy
Undercut WebFX significantly:
- Starter: $500 setup + $99/mo
- Pro: $1,500 setup + $249/mo
- Business: $3,000 setup + $499/mo`,
    createdAt: '2026-02-03T01:00:00Z',
    updatedAt: '2026-02-04T03:30:00Z'
  },
  {
    id: '4',
    name: 'Conduit AI',
    description: 'AI-powered workflow automation and orchestration platform',
    status: 'active',
    githubUrl: 'https://github.com/umbrarelay-maker/conduit-ai',
    vercelUrl: 'https://conduit-ai-two.vercel.app',
    notes: 'DFW chatbot consulting site. Live and functional.',
    details: `## Vision
Conduit AI connects various AI agents and tools into automated workflows. Think Zapier but with AI agents as first-class citizens.

## Core Concepts
- **Triggers**: Events that start workflows
- **Agents**: AI models that process/decide
- **Actions**: External integrations
- **Flows**: Connected sequences

## Use Cases
1. Auto-triage support tickets
2. Content pipeline automation
3. Data processing workflows
4. Multi-agent collaboration

## Status
Early conceptual phase. Defining MVP scope.`,
    createdAt: '2026-02-03T02:00:00Z',
    updatedAt: '2026-02-03T05:00:00Z'
  },
  {
    id: '5',
    name: 'Marketing Plan',
    description: 'Strategic marketing documentation and campaign planning',
    status: 'active',
    notes: 'Drafting initial GTM strategy. Focus on dev community.',
    details: `## Go-to-Market Strategy

### Target Audience
- Developers building AI applications
- Indie hackers and solopreneurs
- Small teams needing AI automation

### Channels
1. **Twitter/X** - Dev community engagement
2. **GitHub** - Open source presence
3. **Discord** - Community building
4. **Blog/Content** - Technical tutorials

### Messaging
"Your AI that actually gets things done"
- Focus on practical utility
- Show real results
- Emphasize collaboration aspect

### Timeline
- Week 1: Core messaging + landing page
- Week 2: Social presence established
- Week 3: First content pieces
- Week 4: Community launch`,
    createdAt: '2026-02-03T03:00:00Z',
    updatedAt: '2026-02-03T05:30:00Z'
  }
];

export const initialDocuments: Document[] = [
  {
    id: '5',
    title: 'AI Discovery Call → CRM Enrichment Plan',
    category: 'technical',
    description: 'Research and implementation plan for using AI to extract structured data from discovery calls and enrich CRM',
    content: `# AI-Powered Discovery Call → Zoho CRM Enrichment

## Executive Summary

Use AI to automatically extract structured data from discovery call notes/transcripts and push enriched data to **Zoho CRM**. This eliminates manual data entry, ensures consistency, and captures insights that might otherwise be missed.

---

## The Problem

After a discovery call, sales reps typically:
1. Have messy notes or a transcript
2. Manually enter key fields into Zoho CRM
3. Miss important details or enter inconsistent data
4. Spend 10-15 minutes per call on data entry

**Result:** Incomplete CRM data, wasted time, lost insights.

---

## The Solution

### Architecture Overview

\`\`\`
Discovery Call
      ↓
Notes/Transcript (text input)
      ↓
AI Extraction (LLM with structured output)
      ↓
Structured JSON
      ↓
Zoho CRM API v6 (create/update records)
\`\`\`

---

## Zoho CRM Field Mapping

### Leads Module (Primary)

| Extracted Field | Zoho API Field | Type | Notes |
|----------------|----------------|------|-------|
| Contact Name | Last_Name, First_Name | String | Last_Name is mandatory |
| Company | Company | String | Max 255 chars |
| Email | Email | String | Validated format |
| Phone | Phone | String | Max 30 chars |
| Title | Designation | String | Job title |
| Industry | Industry | Picklist | Must match existing values |
| Lead Source | Lead_Source | Picklist | e.g., "Cold Call" |
| Annual Revenue | Annual_Revenue | Currency | Double value |
| Website | Website | URL | Must be valid URL |
| City | City | String | |
| State | State | String | |
| Description | Description | Multi-line | Notes/pain points |

### Deals Module (When Qualified)

| Extracted Field | Zoho API Field | Type | Notes |
|----------------|----------------|------|-------|
| Deal Name | Deal_Name | String | Mandatory |
| Stage | Stage | Picklist | Mandatory (e.g., "Qualification") |
| Amount | Amount | Currency | Deal value |
| Closing Date | Closing_Date | Date | yyyy-MM-dd format |
| Pipeline | Pipeline | String | Mandatory if pipelines enabled |
| Probability | Probability | Integer | 0-100 |
| Next Step | Next_Step | String | Follow-up action |

### Contacts Module

| Extracted Field | Zoho API Field | Type | Notes |
|----------------|----------------|------|-------|
| Full Name | Last_Name, First_Name | String | Last_Name mandatory |
| Email | Email | String | |
| Phone | Phone | String | |
| Mobile | Mobile | String | |
| Title | Title | String | |
| Department | Department | String | |
| Account | Account_Name | Lookup | Link to Accounts module |

---

## Zoho CRM API Integration

### Authentication (OAuth 2.0)

Zoho uses OAuth 2.0. You'll need:
- **Client ID** — From Zoho API Console
- **Client Secret** — From Zoho API Console
- **Refresh Token** — For long-lived access

\`\`\`javascript
// Token refresh
const tokenResponse = await fetch('https://accounts.zoho.com/oauth/v2/token', {
  method: 'POST',
  headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  body: new URLSearchParams({
    refresh_token: ZOHO_REFRESH_TOKEN,
    client_id: ZOHO_CLIENT_ID,
    client_secret: ZOHO_CLIENT_SECRET,
    grant_type: 'refresh_token'
  })
});
const { access_token } = await tokenResponse.json();
\`\`\`

### Required Scopes
\`\`\`
ZohoCRM.modules.leads.CREATE
ZohoCRM.modules.leads.UPDATE
ZohoCRM.modules.deals.CREATE
ZohoCRM.modules.deals.UPDATE
ZohoCRM.modules.contacts.CREATE
ZohoCRM.modules.contacts.UPDATE
ZohoCRM.modules.accounts.CREATE
ZohoCRM.modules.accounts.UPDATE
\`\`\`

### Insert Lead Example

\`\`\`javascript
const createLead = async (extractedData, accessToken) => {
  const response = await fetch('https://www.zohoapis.com/crm/v6/Leads', {
    method: 'POST',
    headers: {
      'Authorization': \\\`Zoho-oauthtoken \\\${accessToken}\\\`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      data: [{
        Last_Name: extractedData.contact_name.split(' ').pop(),
        First_Name: extractedData.contact_name.split(' ').slice(0, -1).join(' '),
        Company: extractedData.company_name,
        Email: extractedData.email,
        Phone: extractedData.phone,
        Designation: extractedData.title,
        Industry: extractedData.industry,
        Lead_Source: 'Discovery Call',
        Annual_Revenue: extractedData.annual_revenue,
        Website: extractedData.website,
        City: extractedData.city,
        State: extractedData.state,
        Description: extractedData.pain_points?.join('\\n') || ''
      }],
      trigger: ['workflow']  // Trigger Zoho workflows
    })
  });
  return response.json();
};
\`\`\`

### Update Existing Record

\`\`\`javascript
const updateLead = async (recordId, extractedData, accessToken) => {
  const response = await fetch(\\\`https://www.zohoapis.com/crm/v6/Leads/\\\${recordId}\\\`, {
    method: 'PUT',
    headers: {
      'Authorization': \\\`Zoho-oauthtoken \\\${accessToken}\\\`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      data: [{
        id: recordId,
        Description: extractedData.notes,
        // ... other fields to update
      }]
    })
  });
  return response.json();
};
\`\`\`

### Create Deal from Qualified Lead

\`\`\`javascript
const createDeal = async (extractedData, contactId, accessToken) => {
  const response = await fetch('https://www.zohoapis.com/crm/v6/Deals', {
    method: 'POST',
    headers: {
      'Authorization': \\\`Zoho-oauthtoken \\\${accessToken}\\\`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      data: [{
        Deal_Name: \\\`\\\${extractedData.company_name} - \\\${extractedData.product_interest}\\\`,
        Stage: 'Qualification',
        Amount: extractedData.deal_size_estimate,
        Closing_Date: extractedData.expected_close_date, // yyyy-MM-dd
        Contact_Name: { id: contactId },
        Pipeline: 'Standard',
        Probability: 20,
        Next_Step: extractedData.next_steps?.[0] || 'Follow up call',
        Description: \\\`Pain Points: \\\${extractedData.pain_points?.join(', ')}\\n\\nBudget: \\\${extractedData.budget_range}\\n\\nTimeline: \\\${extractedData.timeline}\\\`
      }],
      trigger: ['workflow', 'blueprint']
    })
  });
  return response.json();
};
\`\`\`

---

## What Data to Extract

### Company Information
- **Company Name** — Legal name and DBA → \\\`Company\\\`
- **Website** — Primary domain → \\\`Website\\\`
- **Industry** — Vertical/sector → \\\`Industry\\\` (picklist)
- **Company Size** — Employee count → \\\`No_of_Employees\\\`
- **Annual Revenue** — If mentioned → \\\`Annual_Revenue\\\`
- **Location** — City/State → \\\`City\\\`, \\\`State\\\`

### Contact Information
- **Contact Name** — Full name → \\\`First_Name\\\`, \\\`Last_Name\\\`
- **Title/Role** — Job title → \\\`Designation\\\`
- **Email** — If mentioned → \\\`Email\\\`
- **Phone** — If mentioned → \\\`Phone\\\`
- **Decision Maker?** — Yes/No → Custom field or \\\`Description\\\`

### Opportunity Details
- **Pain Points** — Challenges → \\\`Description\\\`
- **Current Solution** — What they use → Custom field
- **Budget Range** — If discussed → \\\`Amount\\\` (Deals)
- **Timeline** — When needed → \\\`Closing_Date\\\` (Deals)
- **Deal Size Estimate** — Value → \\\`Amount\\\` (Deals)

### Qualification (BANT/MEDDIC)
- **Budget** — Confirmed/Unknown → Custom field or notes
- **Authority** — Decision maker? → Custom field
- **Need** — Urgency level → \\\`Rating\\\` (picklist)
- **Timeline** — When → \\\`Closing_Date\\\`

### Next Steps
- **Follow-up Date** → \\\`Next_Step\\\`, create Task
- **Materials Requested** → Create Task with details

---

## AI Extraction Prompt

\`\`\`javascript
const EXTRACTION_PROMPT = \\\`
You are a CRM data extraction assistant. Extract structured data from discovery call notes for Zoho CRM.

Return a JSON object with these fields:
{
  "contact": {
    "first_name": "string",
    "last_name": "string (REQUIRED)",
    "email": "string or null",
    "phone": "string or null",
    "title": "string or null"
  },
  "company": {
    "name": "string (REQUIRED)",
    "website": "valid URL or null",
    "industry": "string or null",
    "employee_count": "number or null",
    "annual_revenue": "number or null",
    "city": "string or null",
    "state": "string or null"
  },
  "opportunity": {
    "pain_points": ["array of strings"],
    "current_solution": "string or null",
    "budget_range": "string or null",
    "budget_confirmed": true/false/null,
    "timeline": "string or null",
    "deal_size_estimate": "number or null",
    "competitors_mentioned": ["array of strings"]
  },
  "qualification": {
    "decision_maker": true/false/null,
    "urgency": "high/medium/low/unknown",
    "next_steps": ["array of strings"],
    "follow_up_date": "yyyy-MM-dd or null",
    "materials_requested": ["array of strings"]
  },
  "sentiment": {
    "engagement_level": "high/medium/low",
    "buying_signals": ["array of strings"],
    "objections": ["array of strings"],
    "overall": "positive/neutral/negative"
  }
}

Rules:
- Extract only explicitly mentioned information
- Use null for fields not mentioned
- last_name and company.name are required - infer if necessary
- Dates in yyyy-MM-dd format
- Revenue/deal size as numbers without currency symbols
- Industry should match common CRM picklist values
\\\`;
\`\`\`

---

## Implementation Approach

### Option 1: Simple Prompt + JSON Mode (Recommended to Start)

\`\`\`javascript
const response = await openai.chat.completions.create({
  model: "gpt-4o",
  response_format: { type: "json_object" },
  messages: [
    { role: "system", content: EXTRACTION_PROMPT },
    { role: "user", content: callNotes }
  ]
});

const extracted = JSON.parse(response.choices[0].message.content);
\`\`\`

### Option 2: Function Calling (More Robust)
Use OpenAI function calling for guaranteed schema compliance.

---

## Workflow Options

1. **Manual Trigger** — Paste notes, review extracted data, confirm push to Zoho
2. **Semi-Automated** — Transcript auto-sent, review in UI, one-click approve
3. **Fully Automated** — Auto-process and push to Zoho CRM

**Recommendation:** Start with Manual Trigger, graduate to Semi-Automated.

---

## Zoho-Specific Considerations

### Duplicate Handling
Zoho checks for duplicates on unique fields (Email). Handle the \\\`DUPLICATE_DATA\\\` error:
\`\`\`javascript
if (response.data[0].code === 'DUPLICATE_DATA') {
  // Search for existing record and update instead
  const existingId = response.data[0].details.id;
  return updateLead(existingId, extractedData, accessToken);
}
\`\`\`

### Workflow Triggers
Use the \\\`trigger\\\` array to control automation:
- \\\`workflow\\\` — Trigger workflow rules
- \\\`blueprint\\\` — Trigger blueprints
- \\\`approval\\\` — Trigger approval processes
- Set to \\\`[]\\\` to skip all automation

### Rate Limits
- 100 records per API call
- 15,000 API calls per day (varies by plan)
- Use batch operations when possible

### Custom Fields
For fields not in standard modules, create custom fields in Zoho:
1. Settings → Customization → Modules → Leads
2. Add custom fields for: \\\`Budget_Confirmed\\\`, \\\`Current_Solution\\\`, etc.
3. Get field API names from Developer Hub → API Names

---

## Tech Stack Recommendation

| Component | Tool |
|-----------|------|
| AI Extraction | OpenAI GPT-4o |
| Backend | Next.js API routes |
| Transcript Source | Fireflies.ai, Gong, or Otter.ai |
| CRM | Zoho CRM |
| Auth | Zoho OAuth 2.0 |

---

## MVP Implementation Plan

### Phase 1: Proof of Concept (1-2 days)
- Build web form for pasting call notes
- Implement extraction prompt with JSON mode
- Display extracted data mapped to Zoho fields

### Phase 2: Zoho Integration (2-3 days)
- Register app in Zoho API Console
- Implement OAuth 2.0 flow
- Map extracted fields to Zoho schema
- One-click push to Leads module

### Phase 3: Automation (3-5 days)
- Webhook endpoint for transcript services
- Background processing queue
- Deal creation workflow
- Task creation for follow-ups

---

## Cost Estimate

| Item | Cost |
|------|------|
| OpenAI GPT-4o | ~$0.01-0.03 per call |
| Transcript service | $15-30/mo |
| Hosting | ~$0 (Vercel free tier) |
| Zoho CRM | Existing subscription |

**Total:** ~$20-50/month + pennies per extraction

---

## Zoho API Quick Reference

**Base URL:** \\\`https://www.zohoapis.com/crm/v6/\\\`

**Auth Header:** \\\`Authorization: Zoho-oauthtoken {access_token}\\\`

**Key Endpoints:**
- Insert: \\\`POST /crm/v6/{module}\\\`
- Update: \\\`PUT /crm/v6/{module}/{id}\\\`
- Search: \\\`GET /crm/v6/{module}/search?criteria=...\\\`
- Get Fields: \\\`GET /crm/v6/settings/fields?module={module}\\\`

**Docs:** https://www.zoho.com/crm/developer/docs/api/v6/

---

## Next Steps

1. ✅ Zoho CRM field mapping complete
2. Register OAuth app in Zoho API Console
3. Get 3-5 sample call transcripts
4. Build extraction POC
5. Test with real Zoho data

---

*Document created: 2026-02-04*
*Updated: 2026-02-04 — Zoho CRM integration details added*
*Author: Umbra*`,
    createdAt: '2026-02-04T03:45:00Z'
  },
  {
    id: '1',
    title: 'Project Audit Report',
    category: 'audits',
    description: 'Comprehensive audit of current project states and priorities',
    content: `# Project Audit Report
**Date:** February 3, 2026
**Author:** Umbra

## Executive Summary
All five active projects are in healthy states with clear next steps defined. No critical blockers identified.

## Project Status Overview

| Project | Status | Health | Priority |
|---------|--------|--------|----------|
| Demo Site | Active | 🟢 Good | High |
| Report Viewer | Active | 🟢 Good | Medium |
| Chatbot Framework | Active | 🟡 Needs Attention | High |
| Conduit AI | Active | 🟢 Good | Low |
| Marketing Plan | Active | 🟢 Good | Medium |

## Recommendations
1. Prioritize Demo Site for public launch
2. Complete Chatbot Framework core before expanding
3. Begin Marketing Plan execution in parallel

## Risk Assessment
- **Low Risk**: Most projects on track
- **Watch**: Chatbot Framework complexity`,
    createdAt: '2026-02-03T04:00:00Z'
  },
  {
    id: '2',
    title: 'AI Landscape Research',
    category: 'research',
    description: 'Analysis of current AI tools and market positioning',
    content: `# AI Landscape Research
**Date:** February 3, 2026

## Market Overview
The AI agent/assistant space is rapidly evolving. Key players include:

### Direct Competitors
- **Cursor** - AI-powered IDE
- **Devin** - Autonomous coding agent
- **AutoGPT** - Open source agent framework
- **Claude Projects** - Anthropic's workspace feature

### Our Differentiation
1. **True autonomy** - Not just code completion
2. **Multi-modal** - Code, research, communication
3. **Persistent context** - Learns and remembers
4. **Human collaboration** - Not replacement

## Opportunities
- Gap in "AI teammate" positioning
- Developers want capable, not clever
- Trust through transparency

## Threats
- Big players moving fast
- Commoditization of basic AI features`,
    createdAt: '2026-02-03T03:30:00Z'
  },
  {
    id: '3',
    title: 'Go-to-Market Strategy',
    category: 'marketing',
    description: 'Initial marketing strategy for Umbra ecosystem',
    content: `# Go-to-Market Strategy
**Version:** 1.0
**Date:** February 3, 2026

## Vision
Position Umbra as the AI teammate that developers actually want to work with.

## Target Segments

### Primary: Indie Developers
- Building side projects
- Value speed and capability
- Active on Twitter, HN, Reddit

### Secondary: Small Teams
- 2-10 person startups
- Need force multiplication
- Budget conscious

## Launch Strategy

### Phase 1: Stealth (Now)
- Build core products
- Establish infrastructure
- Create demo content

### Phase 2: Soft Launch
- Share on Twitter
- Post to HN
- Discord community

### Phase 3: Growth
- Content marketing
- Partnerships
- Paid acquisition test`,
    createdAt: '2026-02-03T05:00:00Z'
  },
  {
    id: '4',
    title: 'Architecture Overview',
    category: 'technical',
    description: 'Technical architecture documentation for all systems',
    content: `# Technical Architecture Overview

## System Components

### Core Infrastructure
- **OpenClaw** - Agent runtime environment
- **Gateway** - API and message routing
- **Workspace** - File and project management

### Deployed Applications
- Next.js apps on Vercel
- GitHub for source control
- Automated CI/CD pipelines

## Tech Stack
- **Frontend**: Next.js, React, Tailwind CSS
- **Backend**: Node.js, API routes
- **AI**: Claude (Anthropic), OpenAI
- **Infra**: Vercel, GitHub Actions

## Security Considerations
- API keys in environment variables
- No secrets in repositories
- Rate limiting on all endpoints

## Scaling Strategy
1. Start with Vercel free tier
2. Monitor usage patterns
3. Optimize before scaling
4. Consider edge functions`,
    createdAt: '2026-02-03T02:00:00Z'
  }
];

export const initialUpdates: Update[] = [
  {
    id: '-5',
    content: 'Fixed document page formatting — consistent rounded-lg, cleaner category badges, tighter spacing throughout',
    timestamp: '2026-02-04T03:55:00Z',
    type: 'task'
  },
  {
    id: '-4',
    content: 'Daily briefing visual refresh — replaced plum gradient with subtle sky-blue, cleaner icons',
    timestamp: '2026-02-04T03:52:00Z',
    type: 'task'
  },
  {
    id: '-3',
    content: '✨ Umbra HQ formal UI refresh — smaller radii, subtler animations, sky-blue/pink accents, more professional feel',
    timestamp: '2026-02-04T03:45:00Z',
    type: 'milestone'
  },
  {
    id: '-2',
    content: '📄 Created "AI Discovery Call → CRM Enrichment" plan document. Full implementation guide for extracting structured data from sales calls using AI and pushing to HubSpot/Salesforce.',
    timestamp: '2026-02-04T03:30:00Z',
    type: 'task'
  },
  {
    id: '-1',
    content: '🚀 Nyx Chat major update: Multi-provider AI (OpenAI/Anthropic/Google), URL import with Readability, client API key support, 7 widget icons, sophisticated dark UI. Ready for auth integration!',
    timestamp: '2026-02-04T03:00:00Z',
    type: 'milestone'
  },
  {
    id: '0',
    content: '🎉 Umbra HQ v2.0 deployed! Full workspace upgrade complete. New features: Rich Text Editor (Tiptap), Kanban Task Board with drag-and-drop, Global Search, Link Library, enhanced Project & Document pages with inline editing. All data persists to localStorage. Supabase integration coming next!',
    timestamp: '2026-02-03T06:00:00Z',
    type: 'milestone'
  },
  {
    id: '1',
    content: '🚀 Created Umbra HQ dashboard - our central collaboration hub is now live!',
    timestamp: '2026-02-03T05:40:00Z',
    type: 'milestone'
  },
  {
    id: '2',
    content: 'Completed initial setup of 5 core projects: Demo Site, Report Viewer, Chatbot Framework, Conduit AI, and Marketing Plan',
    timestamp: '2026-02-03T05:30:00Z',
    type: 'task'
  },
  {
    id: '3',
    content: 'Successfully deployed Report Viewer to Vercel - MVP is functional',
    timestamp: '2026-02-03T04:30:00Z',
    type: 'task'
  },
  {
    id: '4',
    content: 'Architected Chatbot Framework with modular design for pluggable LLM backends',
    timestamp: '2026-02-03T04:00:00Z',
    type: 'task'
  },
  {
    id: '5',
    content: 'Tonight\'s focus: Building out the core infrastructure and getting everything deployed',
    timestamp: '2026-02-03T03:00:00Z',
    type: 'status'
  },
  {
    id: '6',
    content: 'Starting session with Joe - lots to build tonight! 💪',
    timestamp: '2026-02-03T02:00:00Z',
    type: 'status'
  }
];

export const initialQuickLinks: QuickLink[] = [
  {
    id: '1',
    label: 'Nyx Chat',
    url: 'https://chatbot-framework-one.vercel.app',
    category: 'site',
    description: 'AI chatbot platform - main product'
  },
  {
    id: '2',
    label: 'Umbra HQ',
    url: 'https://umbra-hq.vercel.app',
    category: 'site',
    description: 'This dashboard'
  },
  {
    id: '3',
    label: 'Demo Site',
    url: 'https://apex-digital-demo.vercel.app',
    category: 'site',
    description: 'Agency demo showcase'
  },
  {
    id: '4',
    label: 'Demo Site Repo',
    url: 'https://github.com/umbrarelay-maker/demo-site',
    category: 'repo',
    description: 'Source code for demo site'
  },
  {
    id: '5',
    label: 'Report Viewer Repo',
    url: 'https://github.com/umbrarelay-maker/report-viewer',
    category: 'repo',
    description: 'Source code for report viewer'
  },
  {
    id: '6',
    label: 'Chatbot Framework Repo',
    url: 'https://github.com/umbrarelay-maker/chatbot-framework',
    category: 'repo',
    description: 'Modular chatbot framework source'
  },
  {
    id: '7',
    label: 'Conduit AI Repo',
    url: 'https://github.com/umbrarelay-maker/conduit-ai',
    category: 'repo',
    description: 'Workflow automation platform source'
  },
  {
    id: '8',
    label: 'OpenClaw',
    url: 'https://openclaw.dev',
    category: 'tool',
    description: 'Agent runtime environment'
  },
  {
    id: '9',
    label: 'Vercel Dashboard',
    url: 'https://vercel.com/dashboard',
    category: 'tool',
    description: 'Deployment management'
  },
  {
    id: '10',
    label: 'Anthropic Console',
    url: 'https://console.anthropic.com',
    category: 'tool',
    description: 'Claude API management'
  }
];

export const initialBlockers: Blocker[] = [];

export const initialBriefing: DailyBriefing = {
  date: '2026-02-04',
  summary: 'Shipped Nyx Chat with multi-provider AI and refined Umbra HQ\'s design. Both apps now share a cohesive formal aesthetic — smaller radii, sky-blue/pink accents, subtler animations. Ready to test Nyx with real API keys.',
  keyItems: [
    'Nyx Chat rebrand complete with sophisticated dark UI',
    'Multi-provider AI: GPT-5.2, Claude Haiku 4.5, Gemini 3 Flash',
    'Umbra HQ formal UI refresh deployed',
    'URL import feature using Mozilla Readability',
    'Discovery Call → CRM enrichment plan created'
  ],
  whatsNext: [
    'Run SQL schema in Supabase for RAG',
    'Test Nyx Chat with real API key end-to-end',
    'Add auth/accounts to Nyx Chat (Phase 4)',
    'Secure domain (getnyx.ai or usenyx.com)',
    'Review Discovery Call plan with Joe'
  ],
  mood: 'shipping'
};

export const initialTasks: Task[] = [
  {
    id: '0',
    title: 'Run Nyx Chat SQL schema in Supabase',
    description: 'Execute supabase/schema.sql in Supabase SQL Editor to enable RAG',
    status: 'todo',
    priority: 'high',
    projectId: '3',
    createdAt: '2026-02-04T03:55:00Z',
    updatedAt: '2026-02-04T03:55:00Z'
  },
  {
    id: '1',
    title: 'Polish Demo Site hero section',
    description: 'Add animations and improve visual appeal',
    status: 'in-progress',
    priority: 'high',
    projectId: '1',
    createdAt: '2026-02-03T05:00:00Z',
    updatedAt: '2026-02-03T05:00:00Z'
  },
  {
    id: '2',
    title: 'Add live conversation demo',
    description: 'Interactive demo showing Umbra in action',
    status: 'todo',
    priority: 'high',
    projectId: '1',
    createdAt: '2026-02-03T05:00:00Z',
    updatedAt: '2026-02-03T05:00:00Z'
  },
  {
    id: '3',
    title: 'Implement PDF export',
    description: 'Allow users to export reports as PDF',
    status: 'todo',
    priority: 'medium',
    projectId: '2',
    createdAt: '2026-02-03T04:30:00Z',
    updatedAt: '2026-02-03T04:30:00Z'
  },
  {
    id: '4',
    title: 'Complete OpenAI adapter',
    description: 'Finish the OpenAI provider implementation',
    status: 'in-progress',
    priority: 'high',
    projectId: '3',
    createdAt: '2026-02-03T04:00:00Z',
    updatedAt: '2026-02-03T04:00:00Z'
  },
  {
    id: '5',
    title: 'Write Twitter thread about Umbra',
    description: 'Introduction thread for launch',
    status: 'todo',
    priority: 'medium',
    projectId: '5',
    createdAt: '2026-02-03T05:30:00Z',
    updatedAt: '2026-02-03T05:30:00Z'
  },
  {
    id: '6',
    title: 'Set up Vercel analytics',
    status: 'done',
    priority: 'low',
    createdAt: '2026-02-03T03:00:00Z',
    updatedAt: '2026-02-03T04:00:00Z'
  }
];
