// Initial data for Umbra HQ

import { crmEnrichmentContent } from './crm-doc-content';
export interface Project {
  id: string;
  name: string;
  description: string;
  status: 'active' | 'completed' | 'on-hold';
  githubUrl?: string;
  vercelUrl?: string;
  notes: string;
  details?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Document {
  id: string;
  title: string;
  category: 'audits' | 'research' | 'marketing' | 'technical' | 'other';
  url?: string;
  description: string;
  content?: string;
  createdAt: string;
  updatedAt?: string;
}

export interface Update {
  id: string;
  content: string;
  timestamp: string;
  type: 'status' | 'task' | 'note' | 'milestone';
}

export interface QuickLink {
  id: string;
  label: string;
  url: string;
  category: 'site' | 'repo' | 'tool' | 'docs' | 'resource';
  description?: string;
}

export interface Blocker {
  id: string;
  title: string;
  description: string;
  severity: 'critical' | 'high' | 'medium';
  category: 'billing' | 'access' | 'rate-limit' | 'account' | 'technical' | 'other';
  createdAt: string;
  resolved: boolean;
}

export interface DailyBriefing {
  date: string;
  summary: string;
  keyItems: string[];
  whatsNext: string[];
  mood: 'productive' | 'blocked' | 'planning' | 'shipping';
}

export interface Task {
  id: string;
  title: string;
  description?: string;
  status: 'todo' | 'in-progress' | 'done';
  priority: 'low' | 'medium' | 'high';
  projectId?: string;
  createdAt: string;
  updatedAt: string;
}

export const initialProjects: Project[] = [
  {
    id: '1',
    name: 'Demo Site',
    description: 'Interactive demo showcasing Umbra capabilities and features',
    status: 'active',
    githubUrl: 'https://github.com/umbrarelay-maker/apex-digital-demo',
    vercelUrl: 'https://apex-digital-demo.vercel.app',
    notes: 'Main showcase for potential users. Needs polishing.',
    details: `## Overview
The Demo Site serves as the primary showcase for Umbra's capabilities. It demonstrates real-time AI collaboration, tool usage, and autonomous task completion.

## Current State
- Basic structure deployed
- Hero section with feature highlights
- Interactive demo components in progress

## Next Steps
1. Add live demo of conversation flow
2. Showcase tool integrations
3. Add testimonials/use cases section
4. Performance optimization

## Tech Stack
- Next.js 16
- Tailwind CSS
- Framer Motion for animations`,
    createdAt: '2026-02-03T00:00:00Z',
    updatedAt: '2026-02-03T05:00:00Z'
  },
  {
    id: '2',
    name: 'Report Viewer',
    description: 'Web interface for viewing and navigating generated reports',
    status: 'active',
    githubUrl: 'https://github.com/umbrarelay-maker/report-viewer',
    vercelUrl: 'https://report-viewer-two.vercel.app',
    notes: 'Renders markdown reports with navigation. MVP complete.',
    details: `## Overview
A clean, readable interface for viewing markdown reports generated by Umbra. Supports navigation, search, and categorization.

## Current State
- MVP deployed and functional
- Markdown rendering working
- Basic navigation implemented

## Features
- Markdown to HTML conversion
- Table of contents generation
- Print-friendly styling
- Dark/light mode

## Next Steps
1. Add search functionality
2. PDF export option
3. Report comparison view`,
    createdAt: '2026-02-03T00:00:00Z',
    updatedAt: '2026-02-03T04:30:00Z'
  },
  {
    id: '3',
    name: 'Nyx Chat',
    description: 'AI chatbot platform with RAG knowledge base - white-label product for clients',
    status: 'active',
    githubUrl: 'https://github.com/umbrarelay-maker/chatbot-framework',
    vercelUrl: 'https://chatbot-framework-one.vercel.app',
    notes: 'Rebranded to Nyx Chat. Multi-provider AI, RAG pipeline, URL import ready. Needs auth before production.',
    details: `## Overview
Nyx Chat is a white-label AI chatbot platform that clients can configure and embed on their websites. Competes with WebFX's AI Agent services at better pricing.

## Features (Built)
- Multi-provider AI (GPT-5.2, Claude Haiku 4.5, Gemini 3 Flash)
- Client-provided API keys
- Customizable widget (7 icons, brand colors)
- Knowledge base with text paste + URL import
- RAG pipeline (pgvector ready)
- Dark, sophisticated UI

## Tech Stack
- Next.js + Tailwind
- Supabase (pgvector for RAG)
- Mozilla Readability for URL scraping
- OpenAI/Anthropic/Google APIs

## Before Production
- [ ] Auth/accounts (Supabase Auth)
- [ ] API key encryption
- [ ] Run SQL schema in Supabase
- [ ] Test with real API keys
- [ ] Create embeddable widget.js
- [ ] Custom domain (exploring options)

## Pricing Strategy
Undercut WebFX significantly:
- Starter: $500 setup + $99/mo
- Pro: $1,500 setup + $249/mo
- Business: $3,000 setup + $499/mo`,
    createdAt: '2026-02-03T01:00:00Z',
    updatedAt: '2026-02-04T03:30:00Z'
  },
  {
    id: '4',
    name: 'Conduit AI',
    description: 'AI-powered workflow automation and orchestration platform',
    status: 'active',
    githubUrl: 'https://github.com/umbrarelay-maker/conduit-ai',
    vercelUrl: 'https://conduit-ai-two.vercel.app',
    notes: 'DFW chatbot consulting site. Live and functional.',
    details: `## Vision
Conduit AI connects various AI agents and tools into automated workflows. Think Zapier but with AI agents as first-class citizens.

## Core Concepts
- **Triggers**: Events that start workflows
- **Agents**: AI models that process/decide
- **Actions**: External integrations
- **Flows**: Connected sequences

## Use Cases
1. Auto-triage support tickets
2. Content pipeline automation
3. Data processing workflows
4. Multi-agent collaboration

## Status
Early conceptual phase. Defining MVP scope.`,
    createdAt: '2026-02-03T02:00:00Z',
    updatedAt: '2026-02-03T05:00:00Z'
  },
  {
    id: '5',
    name: 'Marketing Plan',
    description: 'Strategic marketing documentation and campaign planning',
    status: 'active',
    notes: 'Drafting initial GTM strategy. Focus on dev community.',
    details: `## Go-to-Market Strategy

### Target Audience
- Developers building AI applications
- Indie hackers and solopreneurs
- Small teams needing AI automation

### Channels
1. **Twitter/X** - Dev community engagement
2. **GitHub** - Open source presence
3. **Discord** - Community building
4. **Blog/Content** - Technical tutorials

### Messaging
"Your AI that actually gets things done"
- Focus on practical utility
- Show real results
- Emphasize collaboration aspect

### Timeline
- Week 1: Core messaging + landing page
- Week 2: Social presence established
- Week 3: First content pieces
- Week 4: Community launch`,
    createdAt: '2026-02-03T03:00:00Z',
    updatedAt: '2026-02-03T05:30:00Z'
  }
];


export const initialDocuments: Document[] = [
  {
    id: '5',
    title: 'Avoma → Zoho CRM Enrichment',
    category: 'technical',
    description: 'Guide for extracting structured data from Avoma call transcripts and enriching Zoho CRM via agent orchestration',
    content: crmEnrichmentContent,
    createdAt: '2026-02-04T03:45:00Z',
    updatedAt: '2026-02-05T02:20:00Z'
  },
  {
    id: '1',
    title: 'Project Audit Report',
    category: 'audits',
    description: 'Comprehensive audit of current project states and priorities',
    content: `# Project Audit Report
**Date:** February 3, 2026
**Author:** Umbra

## Executive Summary
All five active projects are in healthy states with clear next steps defined. No critical blockers identified.

## Project Status Overview

| Project | Status | Health | Priority |
|---------|--------|--------|----------|
| Demo Site | Active | 🟢 Good | High |
| Report Viewer | Active | 🟢 Good | Medium |
| Chatbot Framework | Active | 🟡 Needs Attention | High |
| Conduit AI | Active | 🟢 Good | Low |
| Marketing Plan | Active | 🟢 Good | Medium |

## Recommendations
1. Prioritize Demo Site for public launch
2. Complete Chatbot Framework core before expanding
3. Begin Marketing Plan execution in parallel

## Risk Assessment
- **Low Risk**: Most projects on track
- **Watch**: Chatbot Framework complexity`,
    createdAt: '2026-02-03T04:00:00Z'
  },
  {
    id: '2',
    title: 'AI Landscape Research',
    category: 'research',
    description: 'Analysis of current AI tools and market positioning',
    content: `# AI Landscape Research
**Date:** February 3, 2026

## Market Overview
The AI agent/assistant space is rapidly evolving. Key players include:

### Direct Competitors
- **Cursor** - AI-powered IDE
- **Devin** - Autonomous coding agent
- **AutoGPT** - Open source agent framework
- **Claude Projects** - Anthropic's workspace feature

### Our Differentiation
1. **True autonomy** - Not just code completion
2. **Multi-modal** - Code, research, communication
3. **Persistent context** - Learns and remembers
4. **Human collaboration** - Not replacement

## Opportunities
- Gap in "AI teammate" positioning
- Developers want capable, not clever
- Trust through transparency

## Threats
- Big players moving fast
- Commoditization of basic AI features`,
    createdAt: '2026-02-03T03:30:00Z'
  },
  {
    id: '3',
    title: 'Go-to-Market Strategy',
    category: 'marketing',
    description: 'Initial marketing strategy for Umbra ecosystem',
    content: `# Go-to-Market Strategy
**Version:** 1.0
**Date:** February 3, 2026

## Vision
Position Umbra as the AI teammate that developers actually want to work with.

## Target Segments

### Primary: Indie Developers
- Building side projects
- Value speed and capability
- Active on Twitter, HN, Reddit

### Secondary: Small Teams
- 2-10 person startups
- Need force multiplication
- Budget conscious

## Launch Strategy

### Phase 1: Stealth (Now)
- Build core products
- Establish infrastructure
- Create demo content

### Phase 2: Soft Launch
- Share on Twitter
- Post to HN
- Discord community

### Phase 3: Growth
- Content marketing
- Partnerships
- Paid acquisition test`,
    createdAt: '2026-02-03T05:00:00Z'
  },
  {
    id: '4',
    title: 'Architecture Overview',
    category: 'technical',
    description: 'Technical architecture documentation for all systems',
    content: `# Technical Architecture Overview

## System Components

### Core Infrastructure
- **OpenClaw** - Agent runtime environment
- **Gateway** - API and message routing
- **Workspace** - File and project management

### Deployed Applications
- Next.js apps on Vercel
- GitHub for source control
- Automated CI/CD pipelines

## Tech Stack
- **Frontend**: Next.js, React, Tailwind CSS
- **Backend**: Node.js, API routes
- **AI**: Claude (Anthropic), OpenAI
- **Infra**: Vercel, GitHub Actions

## Security Considerations
- API keys in environment variables
- No secrets in repositories
- Rate limiting on all endpoints

## Scaling Strategy
1. Start with Vercel free tier
2. Monitor usage patterns
3. Optimize before scaling
4. Consider edge functions`,
    createdAt: '2026-02-03T02:00:00Z'
  }
];

export const initialUpdates: Update[] = [
  {
    id: '-5',
    content: 'Fixed document page formatting — consistent rounded-lg, cleaner category badges, tighter spacing throughout',
    timestamp: '2026-02-04T03:55:00Z',
    type: 'task'
  },
  {
    id: '-4',
    content: 'Daily briefing visual refresh — replaced plum gradient with subtle sky-blue, cleaner icons',
    timestamp: '2026-02-04T03:52:00Z',
    type: 'task'
  },
  {
    id: '-3',
    content: '✨ Umbra HQ formal UI refresh — smaller radii, subtler animations, sky-blue/pink accents, more professional feel',
    timestamp: '2026-02-04T03:45:00Z',
    type: 'milestone'
  },
  {
    id: '-2',
    content: '📄 Created "AI Discovery Call → CRM Enrichment" plan document. Full implementation guide for extracting structured data from sales calls using AI and pushing to HubSpot/Salesforce.',
    timestamp: '2026-02-04T03:30:00Z',
    type: 'task'
  },
  {
    id: '-1',
    content: '🚀 Nyx Chat major update: Multi-provider AI (OpenAI/Anthropic/Google), URL import with Readability, client API key support, 7 widget icons, sophisticated dark UI. Ready for auth integration!',
    timestamp: '2026-02-04T03:00:00Z',
    type: 'milestone'
  },
  {
    id: '0',
    content: '🎉 Umbra HQ v2.0 deployed! Full workspace upgrade complete. New features: Rich Text Editor (Tiptap), Kanban Task Board with drag-and-drop, Global Search, Link Library, enhanced Project & Document pages with inline editing. All data persists to localStorage. Supabase integration coming next!',
    timestamp: '2026-02-03T06:00:00Z',
    type: 'milestone'
  },
  {
    id: '1',
    content: '🚀 Created Umbra HQ dashboard - our central collaboration hub is now live!',
    timestamp: '2026-02-03T05:40:00Z',
    type: 'milestone'
  },
  {
    id: '2',
    content: 'Completed initial setup of 5 core projects: Demo Site, Report Viewer, Chatbot Framework, Conduit AI, and Marketing Plan',
    timestamp: '2026-02-03T05:30:00Z',
    type: 'task'
  },
  {
    id: '3',
    content: 'Successfully deployed Report Viewer to Vercel - MVP is functional',
    timestamp: '2026-02-03T04:30:00Z',
    type: 'task'
  },
  {
    id: '4',
    content: 'Architected Chatbot Framework with modular design for pluggable LLM backends',
    timestamp: '2026-02-03T04:00:00Z',
    type: 'task'
  },
  {
    id: '5',
    content: 'Tonight\'s focus: Building out the core infrastructure and getting everything deployed',
    timestamp: '2026-02-03T03:00:00Z',
    type: 'status'
  },
  {
    id: '6',
    content: 'Starting session with Joe - lots to build tonight! 💪',
    timestamp: '2026-02-03T02:00:00Z',
    type: 'status'
  }
];

export const initialQuickLinks: QuickLink[] = [
  {
    id: '1',
    label: 'Nyx Chat',
    url: 'https://chatbot-framework-one.vercel.app',
    category: 'site',
    description: 'AI chatbot platform - main product'
  },
  {
    id: '2',
    label: 'Umbra HQ',
    url: 'https://umbra-hq.vercel.app',
    category: 'site',
    description: 'This dashboard'
  },
  {
    id: '3',
    label: 'Demo Site',
    url: 'https://apex-digital-demo.vercel.app',
    category: 'site',
    description: 'Agency demo showcase'
  },
  {
    id: '4',
    label: 'Demo Site Repo',
    url: 'https://github.com/umbrarelay-maker/demo-site',
    category: 'repo',
    description: 'Source code for demo site'
  },
  {
    id: '5',
    label: 'Report Viewer Repo',
    url: 'https://github.com/umbrarelay-maker/report-viewer',
    category: 'repo',
    description: 'Source code for report viewer'
  },
  {
    id: '6',
    label: 'Chatbot Framework Repo',
    url: 'https://github.com/umbrarelay-maker/chatbot-framework',
    category: 'repo',
    description: 'Modular chatbot framework source'
  },
  {
    id: '7',
    label: 'Conduit AI Repo',
    url: 'https://github.com/umbrarelay-maker/conduit-ai',
    category: 'repo',
    description: 'Workflow automation platform source'
  },
  {
    id: '8',
    label: 'OpenClaw',
    url: 'https://openclaw.dev',
    category: 'tool',
    description: 'Agent runtime environment'
  },
  {
    id: '9',
    label: 'Vercel Dashboard',
    url: 'https://vercel.com/dashboard',
    category: 'tool',
    description: 'Deployment management'
  },
  {
    id: '10',
    label: 'Anthropic Console',
    url: 'https://console.anthropic.com',
    category: 'tool',
    description: 'Claude API management'
  }
];

export const initialBlockers: Blocker[] = [];

export const initialBriefing: DailyBriefing = {
  date: '2026-02-04',
  summary: 'Shipped Nyx Chat with multi-provider AI and refined Umbra HQ\'s design. Both apps now share a cohesive formal aesthetic — smaller radii, sky-blue/pink accents, subtler animations. Ready to test Nyx with real API keys.',
  keyItems: [
    'Nyx Chat rebrand complete with sophisticated dark UI',
    'Multi-provider AI: GPT-5.2, Claude Haiku 4.5, Gemini 3 Flash',
    'Umbra HQ formal UI refresh deployed',
    'URL import feature using Mozilla Readability',
    'Discovery Call → CRM enrichment plan created'
  ],
  whatsNext: [
    'Run SQL schema in Supabase for RAG',
    'Test Nyx Chat with real API key end-to-end',
    'Add auth/accounts to Nyx Chat (Phase 4)',
    'Secure domain (getnyx.ai or usenyx.com)',
    'Review Discovery Call plan with Joe'
  ],
  mood: 'shipping'
};

export const initialTasks: Task[] = [
  {
    id: '0',
    title: 'Run Nyx Chat SQL schema in Supabase',
    description: 'Execute supabase/schema.sql in Supabase SQL Editor to enable RAG',
    status: 'todo',
    priority: 'high',
    projectId: '3',
    createdAt: '2026-02-04T03:55:00Z',
    updatedAt: '2026-02-04T03:55:00Z'
  },
  {
    id: '1',
    title: 'Polish Demo Site hero section',
    description: 'Add animations and improve visual appeal',
    status: 'in-progress',
    priority: 'high',
    projectId: '1',
    createdAt: '2026-02-03T05:00:00Z',
    updatedAt: '2026-02-03T05:00:00Z'
  },
  {
    id: '2',
    title: 'Add live conversation demo',
    description: 'Interactive demo showing Umbra in action',
    status: 'todo',
    priority: 'high',
    projectId: '1',
    createdAt: '2026-02-03T05:00:00Z',
    updatedAt: '2026-02-03T05:00:00Z'
  },
  {
    id: '3',
    title: 'Implement PDF export',
    description: 'Allow users to export reports as PDF',
    status: 'todo',
    priority: 'medium',
    projectId: '2',
    createdAt: '2026-02-03T04:30:00Z',
    updatedAt: '2026-02-03T04:30:00Z'
  },
  {
    id: '4',
    title: 'Complete OpenAI adapter',
    description: 'Finish the OpenAI provider implementation',
    status: 'in-progress',
    priority: 'high',
    projectId: '3',
    createdAt: '2026-02-03T04:00:00Z',
    updatedAt: '2026-02-03T04:00:00Z'
  },
  {
    id: '5',
    title: 'Write Twitter thread about Umbra',
    description: 'Introduction thread for launch',
    status: 'todo',
    priority: 'medium',
    projectId: '5',
    createdAt: '2026-02-03T05:30:00Z',
    updatedAt: '2026-02-03T05:30:00Z'
  },
  {
    id: '6',
    title: 'Set up Vercel analytics',
    status: 'done',
    priority: 'low',
    createdAt: '2026-02-03T03:00:00Z',
    updatedAt: '2026-02-03T04:00:00Z'
  }
];
